/* Total revenue generated by each employee */
SELECT orders.employee_id, concat(Employees.first_name ,' ', Employees.last_name) AS Employee_name,sum(order_details.unit_price * order_details.quantity) AS total_revenue
FROM order_details
join orders on order_details.order_id=orders.order_id
join employees on orders.employee_id=employees.employee_id
group by orders.employee_id;